In [18]:
import numpy as np
import pickle
import os
import pandas as pd

def makeMatrix():
    np.random.seed(20175327)
    matrix=np.round(np.random.random(40)*10)
    matrix[matrix == 0] = np.NaN
    return matrix
    
def savefile(file_path,matrix):
    f=open("matrix.pkl","wb") 
    pickle.dump(matrix,f)
    f.close()
    
def loadfile(file_path):
    try:
        f=open("matrix.pkl","rb")
        data=pickle.load(f)
    except FileNotFoundError as e:
        print(e)
    return data
    
def nanToZero(matrix):
    f=open("matrix.pkl","rb")
    data=pickle.load(f)
    np.nan_to_num(data,copy=False)  
    return data
    
def makeShape(matrix,row,col):

    
def matMul(mat1,mat2):
    
    
def makePandas(matrix):
    matrix=np.floor(np.random.randn(8,8)*10)
    matrix=pd.date_range('20175327',periods=8(index=list('1행2행3행4행5행6행7행8행')))
    columns=list('1열2열3열4열5열6열7열8열')

    
if __name__=="__main__":
    file_path=os.getcwd()+"/matrix.pkl"
    matrix=makeMatrix()
    print(matrix)
    savefile(file_path,matrix)
    
    del matrix
    matrix=loadfile(file_path)
    print(matrix)
    
    matrix=nanToZero(matrix)
    print(matrix)
    
    mat1=makeShape(matrix,8,5)
    print(mat1)
    mat2=makeShape(matrix,5,8)
    print(mat2)
    
    result=matMul(mat1,mat2)
    print(result)
    
    frame=makePandas(result)
    display(frame)

SyntaxError: invalid syntax (<ipython-input-18-19e71fa126b5>, line 23)

In [43]:
import numpy as np
import pickle
import os
import pandas as pd

def makeMatrix():
    np.random.seed(20175327)
    matrix=np.round(np.random.random(40)*10)
    matrix[matrix == 0] = np.NaN
    return matrix
    
def savefile(file_path,matrix):
    f=open("matrix.pkl","wb") 
    pickle.dump(matrix,f)
    f.close()
    
def loadfile(file_path):
    try:
        f=open("matrix.pkl","rb")
        data=pickle.load(f)
    except FileNotFoundError as e:
        print(e)
    return data

def nanToZero(matrix):
    f=open("matrix.pkl","rb")
    data=pickle.load(f)
    np.nan_to_num(data,copy=False)  
    return data

def makeShape(matrix,row,col):
    make = 1
    shape = matrix.shape
    for s in shape:
        make = make*s
    if make != row*col:
        return 0
    a = np.zeros((row,col))
    for i in range(row):
        a[i] = matrix[i*col:(i+1)*col]
    return a

def matMul(mat1,mat2):
    if mat1.shape[1] != mat2.shape[0]:
        return 0
    a = np.zeros((mat1.shape[0],mat2.shape[1]))
    for i in range(mat1.shape[0]):
        for j in range(mat2.shape[1]):
            a[i][j] = np.sum(mat1[i,:] * mat2[:,j])
    return a

def makePandas(matrix):
    shape = matrix.shape
    frame = pd.DataFrame()
    index = [str((i+1)) + '행' 
             for i in range(shape[0])]
    col = [str((i+1)) + '열' 
           for i in range(shape[1])]
    for i in range(0,len(col)):
        frame[col[i]] = matrix[:,i]
    frame.index = index
    return frame

if __name__=="__main__":
    file_path=os.getcwd()+"/matrix.pkl"
    matrix=makeMatrix()
    print(matrix)
    savefile(file_path,matrix)
    
    del matrix
    matrix=loadfile(file_path)
    print(matrix)
    
    matrix=nanToZero(matrix)
    print(matrix)
    
    mat1=makeShape(matrix,8,5)
    print(mat1)
    mat2=makeShape(matrix,5,8)
    print(mat2)
    
    result=matMul(mat1,mat2)
    print(result)

    frame=makePandas(result)
    display(frame)

[ 6.  3.  1.  8.  2. 10.  9.  6.  2.  4.  4. nan  7.  5.  9. nan  8.  6.
  8. 10.  2.  1.  9.  4.  5.  7.  3.  7.  5.  4.  5.  2. nan  5.  5. nan
  7. nan  2.  6.]
[ 6.  3.  1.  8.  2. 10.  9.  6.  2.  4.  4. nan  7.  5.  9. nan  8.  6.
  8. 10.  2.  1.  9.  4.  5.  7.  3.  7.  5.  4.  5.  2. nan  5.  5. nan
  7. nan  2.  6.]
[ 6.  3.  1.  8.  2. 10.  9.  6.  2.  4.  4.  0.  7.  5.  9.  0.  8.  6.
  8. 10.  2.  1.  9.  4.  5.  7.  3.  7.  5.  4.  5.  2.  0.  5.  5.  0.
  7.  0.  2.  6.]
[[ 6.  3.  1.  8.  2.]
 [10.  9.  6.  2.  4.]
 [ 4.  0.  7.  5.  9.]
 [ 0.  8.  6.  8. 10.]
 [ 2.  1.  9.  4.  5.]
 [ 7.  3.  7.  5.  4.]
 [ 5.  2.  0.  5.  5.]
 [ 0.  7.  0.  2.  6.]]
[[ 6.  3.  1.  8.  2. 10.  9.  6.]
 [ 2.  4.  4.  0.  7.  5.  9.  0.]
 [ 8.  6.  8. 10.  2.  1.  9.  4.]
 [ 5.  7.  3.  7.  5.  4.  5.  2.]
 [ 0.  5.  5.  0.  7.  0.  2.  6.]]
[[ 90. 102.  60. 114.  89. 108. 134.  68.]
 [136. 136. 120. 154. 133. 159. 243. 112.]
 [105. 134. 120. 137. 110.  67. 142. 116.]
 [104. 174. 154. 1

1열     2열     3열     4열     5열     6열     7열     8열
1행   90.0  102.0   60.0  114.0   89.0  108.0  134.0   68.0
2행  136.0  136.0  120.0  154.0  133.0  159.0  243.0  112.0
3행  105.0  134.0  120.0  137.0  110.0   67.0  142.0  116.0
4행  104.0  174.0  154.0  116.0  178.0   78.0  186.0  100.0
5행  106.0  117.0  115.0  134.0   84.0   50.0  138.0   86.0
6행  129.0  130.0  110.0  161.0  102.0  112.0  186.0  104.0
7행   59.0   83.0   53.0   75.0   84.0   80.0   98.0   70.0
8행   24.0   72.0   64.0   14.0  101.0   43.0   85.0   40.0